version: "3.0"
services:
  db:
    container_name: "convert"
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5434:5432"
    networks:
      - custom
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - API_REDIS_HOST=redis
    volumes:
      - .:/fastapi_app
    ports:
      - "8000:8000"
    networks:
      - custom
    command: bash -c "poetry run aerich upgrade && poetry run uvicorn app:create_app --host 0.0.0.0 --port 8000 --reload"

  redis:
    container_name: redis
    image: redis:latest

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "6380:6379"
    networks:
      - custom
networks:
  custom:
volumes:
  fastapi_app: